### ISSUE TITLE
404, particle theme

### ISSUE THREAD

**Issue by FutureLearnSole** [getzola/themes#112]
**particle** repo link needs water... 404 on this page 

<https://www.getzola.org/themes/particle/>

<https://github.com/svavs/particle> **404**

fyip: @svavs @Jieiku 

_Assalamualaikum_

**Comment by Jieiku** [comment]
its actually https://github.com/svavs/particle-zola
It is not my repo but I did submit a pull request a while back: https://github.com/svavs/particle-zola/pull/5/files

**Comment by svavs** [comment]
Yes, my fault. I'm sorry @Jieiku , I'm quite busy in this period. I'll check the pending pull requests as soon as I can 🙏

Thank you for your contribution.

**Comment by goingforbrooke** [comment]
woohoo, you beat [me](https://github.com/getzola/zola/pull/2199) to it. 🎉
