### ISSUE TITLE
theme update action didn't trigger PR action

### ISSUE THREAD

**Issue by emilioziniades** [getzola/themes#140]
I see the "update all themes" action ran successfully this morning. However it didn't trigger the other action that creates the PR to the main zola repo. 

Digging around, I came across this answer:
https://github.com/orgs/community/discussions/27598#discussioncomment-3279511
> If you want the push from an action to trigger another action, you need to create a PAT and use that to authorize the push

Not sure if you want to setup a PAT to be used in the action? If you do, then it would be pretty straightforward to update the action. I'll gladly make the PR.

```diff
name: Update all themes

on:
  workflow_dispatch:
  schedule:
    - cron: "51 5 * * 1"

jobs:
  update-all-themes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
+         token: ${{ secrets.GH_PAT }}
      - name: Update submodules
        run: "git submodule update --remote"
      - name: Commit and push changes
        run: |
          git status
          if [[ `git status --short` ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Update all themes"
            git push
          fi
```

**Comment by Keats** [comment]
Can we have the action open a PR instead? this way we can reuse the current other action

**Comment by emilioziniades** [comment]
Yeah that makes sense

**Comment by emilioziniades** [comment]
I went a bit of a different route here- instead of having the action open a PR, it just invokes the other workflow after pushing the changes to master. I thought this made more sense, since this way you only need to merge 1 PR (getzola/zola), instead of 2 PRs (in getzola/themes and then getzola/zola).

If you don't like this approach, I'm happy to change it to what you suggested above.
