### ISSUE TITLE
[feature] automatize site generation after merge

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [getzola/themes#19]
If someone has experience with GitHub automation, it would be nice to generate automatically the theme site after a merge occurs in master.

**Comment by Keats** [comment]
That would be very nice.

**Comment by zbrox** [comment]
This shouldn't be hard to do, I think I can quickly put something together when I have time maybe over the weekend. Probably the only question I think I have is when the site is generated, should it just be saved as a built artifact from the action or should be uploaded somewhere?

**Comment by Keats** [comment]
The output needs to be committed in https://github.com/getzola/zola since that's where the documentation is.
The first step would be to have some CI that highlights which themes are invalid since I keep missing things when I check manually.

**Comment by zbrox** [comment]
If any of the `zola check`s for themes fail with an error we fail the whole build, right? The other option I guess is to exclude that theme from the build, but I don't know if the current generator script supports it.

**Comment by Keats** [comment]
Right now the script just ignores invalid themes and reports them. No reason to block a deploy because one theme is missing something.

**Comment by zbrox** [comment]
I was mostly referring to the validity check you mentioned in the previous comment. I understood it as running `zola check` on each theme, before running the generator Python script. And when I ran `zola check` on each individual theme, it fails for at least one. Should we just ignore these failures and skip those themes?

**Comment by Keats** [comment]
Ah no sorry, I didn't mean `zola check`, I meant the generator Python script. This repo is not aware of Zola, it only checks for files and keys in a couple of TOML files. No need for `zola check` here, just that the script can generate the theme page since that would mean it's probably fine.

The CI would be mainly checking that we are not adding themes that are invalid, because I didn't run the script manually and missed something like https://github.com/carpetscheme/lightspeed/pull/1

**Comment by zbrox** [comment]
Ah, gotcha :) I made a couple of fixes in the script btw because of `lightspeed` as well. Should I commit those beforehand?

**Comment by Hugo-Trentesaux** [comment]
On the [24 themes](https://github.com/getzola/themes/) present in the repo, only [15 appear](https://www.getzola.org/themes/) on the theme page. Is there a problem somewhere?

**Comment by zbrox** [comment]
I think the latest generated themes site pull request is not merged yet.

**Comment by Keats** [comment]
I've merged it now

**Comment by Hugo-Trentesaux** [comment]
Now it's 22/24 :D

**Comment by zbrox** [comment]
> Now it's 22/24 :D

There are 2 themes which have errors so they get excluded by the generation script.

**Comment by zbrox** [comment]
In the output of the latest run of the action, in the "Run the generator script" step, you can see the themes with errors.

It is `zerm` because it's missing a screenshot and `lightspeed` is missing the name property in its metadata.

**Comment by zbrox** [comment]
@Keats I guess this can be closed as resolved?

**Comment by ejmg** [comment]
@zbrox where/how do I not generate a proper screenshot for zerm? I have some in the repository already and there is a deployed sample site at https://zerm.ejmg.now.sh/, so it's not like i can't just make another one as needed.

**Comment by ejmg** [comment]
alright, i've updated master to have a plain [screenshot.png](https://github.com/ejmg/zerm/blob/master/screenshot.png). hope that fixes it? @Keats

**Comment by zbrox** [comment]
@ejmg the zerm submodule is still pointing to the older commit, so i'll push a pull request updating it to the current master in a sec

**Comment by zbrox** [comment]
@ejmg Zerm is parsed and included in the generated theme site properly now. https://github.com/getzola/themes/runs/966061273?check_suite_focus=true

Next time @Keats merges a pull request from the themes repo it will show up on getzola.org.

**Comment by ejmg** [comment]
@zbrox you are totally fine, sorry on my part for randomly popping up and @'ing about my theme :sweat_smile: 

I randomly remembered that my theme didn't get generated on zola and revisited to see if any developments occurred, rest is now history. Thanks for helping to get it working :slightly_smiling_face:
